package neu.edu.entity;
// Generated Nov 23, 2016 1:00:50 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * AboutMeTable generated by hbm2java
 */
public class AboutMeTable implements java.io.Serializable {

	private String userName;
	private String aboutMe;

	public AboutMeTable() {
	}

	public AboutMeTable(String userName) {
		this.userName = userName;
	}

	public AboutMeTable(String userName, String aboutMe) {
		this.userName = userName;
		this.aboutMe = aboutMe;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getAboutMe() {
		return this.aboutMe;
	}

	public void setAboutMe(String aboutMe) {
		this.aboutMe = aboutMe;
	}

}
