package neu.edu.entity;
// Generated Nov 23, 2016 1:00:50 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * AddressTable generated by hbm2java
 */
public class AddressTable implements java.io.Serializable {

	private String userName;
	private String street;
	private String country;
	private String state;
	private String city;
	private String zipcode;

	public AddressTable() {
	}

	public AddressTable(String userName) {
		this.userName = userName;
	}

	public AddressTable(String userName, String street, String country, String state, String city, String zipcode) {
		this.userName = userName;
		this.street = street;
		this.country = country;
		this.state = state;
		this.city = city;
		this.zipcode = zipcode;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

}
