package neu.edu.entity;
// Generated Nov 23, 2016 1:00:50 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * EducationTable generated by hbm2java
 */
public class EducationTable implements java.io.Serializable {

	private String userName;
	private String graduateSchoolName;
	private String underGraduateSchoolName;
	private String graduateMajor;
	private String underGraduateMajor;
	private String graduateCourses;
	private String underGraduateCourses;
	private Float graduatecgpa;
	private Float underGraduatecgpa;

	public EducationTable() {
	}

	public EducationTable(String userName) {
		this.userName = userName;
	}

	public EducationTable(String userName, String graduateSchoolName, String underGraduateSchoolName,
			String graduateMajor, String underGraduateMajor, String graduateCourses, String underGraduateCourses,
			Float graduatecgpa, Float underGraduatecgpa) {
		this.userName = userName;
		this.graduateSchoolName = graduateSchoolName;
		this.underGraduateSchoolName = underGraduateSchoolName;
		this.graduateMajor = graduateMajor;
		this.underGraduateMajor = underGraduateMajor;
		this.graduateCourses = graduateCourses;
		this.underGraduateCourses = underGraduateCourses;
		this.graduatecgpa = graduatecgpa;
		this.underGraduatecgpa = underGraduatecgpa;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getGraduateSchoolName() {
		return this.graduateSchoolName;
	}

	public void setGraduateSchoolName(String graduateSchoolName) {
		this.graduateSchoolName = graduateSchoolName;
	}

	public String getUnderGraduateSchoolName() {
		return this.underGraduateSchoolName;
	}

	public void setUnderGraduateSchoolName(String underGraduateSchoolName) {
		this.underGraduateSchoolName = underGraduateSchoolName;
	}

	public String getGraduateMajor() {
		return this.graduateMajor;
	}

	public void setGraduateMajor(String graduateMajor) {
		this.graduateMajor = graduateMajor;
	}

	public String getUnderGraduateMajor() {
		return this.underGraduateMajor;
	}

	public void setUnderGraduateMajor(String underGraduateMajor) {
		this.underGraduateMajor = underGraduateMajor;
	}

	public String getGraduateCourses() {
		return this.graduateCourses;
	}

	public void setGraduateCourses(String graduateCourses) {
		this.graduateCourses = graduateCourses;
	}

	public String getUnderGraduateCourses() {
		return this.underGraduateCourses;
	}

	public void setUnderGraduateCourses(String underGraduateCourses) {
		this.underGraduateCourses = underGraduateCourses;
	}

	public Float getGraduatecgpa() {
		return this.graduatecgpa;
	}

	public void setGraduatecgpa(Float graduatecgpa) {
		this.graduatecgpa = graduatecgpa;
	}

	public Float getUnderGraduatecgpa() {
		return this.underGraduatecgpa;
	}

	public void setUnderGraduatecgpa(Float underGraduatecgpa) {
		this.underGraduatecgpa = underGraduatecgpa;
	}

}
