package neu.edu.entity;
// Generated Nov 23, 2016 1:00:50 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * SkillTable generated by hbm2java
 */
public class SkillTable implements java.io.Serializable {

	private String userName;
	private String skill1;
	private Integer skill1rating;
	private String skill2;
	private Integer skill2rating;
	private String skill3;
	private Integer skill3rating;
	private String skill4;
	private Integer skill4rating;
	private String skill5;
	private Integer skill5rating;

	public SkillTable() {
	}

	public SkillTable(String userName) {
		this.userName = userName;
	}

	public SkillTable(String userName, String skill1, Integer skill1rating, String skill2, Integer skill2rating,
			String skill3, Integer skill3rating, String skill4, Integer skill4rating, String skill5,
			Integer skill5rating) {
		this.userName = userName;
		this.skill1 = skill1;
		this.skill1rating = skill1rating;
		this.skill2 = skill2;
		this.skill2rating = skill2rating;
		this.skill3 = skill3;
		this.skill3rating = skill3rating;
		this.skill4 = skill4;
		this.skill4rating = skill4rating;
		this.skill5 = skill5;
		this.skill5rating = skill5rating;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getSkill1() {
		return this.skill1;
	}

	public void setSkill1(String skill1) {
		this.skill1 = skill1;
	}

	public Integer getSkill1rating() {
		return this.skill1rating;
	}

	public void setSkill1rating(Integer skill1rating) {
		this.skill1rating = skill1rating;
	}

	public String getSkill2() {
		return this.skill2;
	}

	public void setSkill2(String skill2) {
		this.skill2 = skill2;
	}

	public Integer getSkill2rating() {
		return this.skill2rating;
	}

	public void setSkill2rating(Integer skill2rating) {
		this.skill2rating = skill2rating;
	}

	public String getSkill3() {
		return this.skill3;
	}

	public void setSkill3(String skill3) {
		this.skill3 = skill3;
	}

	public Integer getSkill3rating() {
		return this.skill3rating;
	}

	public void setSkill3rating(Integer skill3rating) {
		this.skill3rating = skill3rating;
	}

	public String getSkill4() {
		return this.skill4;
	}

	public void setSkill4(String skill4) {
		this.skill4 = skill4;
	}

	public Integer getSkill4rating() {
		return this.skill4rating;
	}

	public void setSkill4rating(Integer skill4rating) {
		this.skill4rating = skill4rating;
	}

	public String getSkill5() {
		return this.skill5;
	}

	public void setSkill5(String skill5) {
		this.skill5 = skill5;
	}

	public Integer getSkill5rating() {
		return this.skill5rating;
	}

	public void setSkill5rating(Integer skill5rating) {
		this.skill5rating = skill5rating;
	}

}
