package neu.edu.entity;
// Generated Nov 23, 2016 1:00:50 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * UserSessionTable generated by hbm2java
 */
public class UserSessionTable implements java.io.Serializable {

	private String userName;
	private Byte isActive;
	private String sessionIdvariable;

	public UserSessionTable() {
	}

	public UserSessionTable(String userName) {
		this.userName = userName;
	}

	public UserSessionTable(String userName, Byte isActive, String sessionIdvariable) {
		this.userName = userName;
		this.isActive = isActive;
		this.sessionIdvariable = sessionIdvariable;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	public String getSessionIdvariable() {
		return this.sessionIdvariable;
	}

	public void setSessionIdvariable(String sessionIdvariable) {
		this.sessionIdvariable = sessionIdvariable;
	}

}
